# Generated by Django 4.0.3 on 2022-04-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowplowrouting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMachinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('tank_capacity', models.FloatField()),
                ('consumption', models.FloatField()),
                ('ready', models.BooleanField(default=False)),
            ],
        ),
    ]
