# Generated by Django 4.0.3 on 2022-04-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowplowrouting', '0003_rename_series_addmachinery_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmachinery',
            name='vin',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
