# Generated by Django 4.0.3 on 2022-04-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowplowrouting', '0004_alter_addmachinery_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addemployee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='addmachinery',
            name='id',
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='email',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addmachinery',
            name='vin',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
