# Generated by Django 4.0.3 on 2022-04-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowplowrouting', '0006_rename_addemployee_employee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='InviteEmployee',
        ),
    ]
