# Generated by Django 4.0.3 on 2022-04-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowplowrouting', '0008_machinery_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='county',
            field=models.CharField(default='temp', max_length=50),
        ),
    ]
