# Generated by Django 4.0.3 on 2022-04-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowplowrouting', '0009_machinery_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='vin',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
