# Generated by Django 4.0.3 on 2022-05-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowplowrouting', '0012_vehiclesaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinery',
            old_name='driver_id',
            new_name='driver_id1',
        ),
        migrations.AddField(
            model_name='machinery',
            name='driver_id2',
            field=models.IntegerField(null=True),
        ),
    ]
