# Generated by Django 4.0.3 on 2022-05-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowplowrouting', '0013_rename_driver_id_machinery_driver_id1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='machinery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowplowrouting.machinery'),
        ),
    ]
