# Generated by Django 4.0.3 on 2022-05-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowplowrouting', '0014_alter_driver_machinery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('city', models.CharField(default='temp', max_length=50)),
            ],
        ),
    ]
