# Generated by Django 4.0.3 on 2022-06-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowplowrouting', '0017_alter_driver_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snowplowrouting.schedule'),
        ),
    ]
