# Generated by Django 4.0.3 on 2022-06-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowplowrouting', '0018_alter_driver_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='route',
            field=models.TextField(null=True),
        ),
    ]
